routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route("home");
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/test-statistic', 'HomeController@test_statistic')->name('test-statistic');

Route::group(["prefix" => "app", "middleware" => "auth"], function () {
    Route::resource('/profile', 'ProfileController');
    Route::resource('/useractivities', 'UserActivityController');
    Route::resource('/activities', 'ActivityController');
    Route::resource('/cards', 'CardController');
    Route::resource('/tasks', 'TaskController');
    Route::resource('/customers', 'CustomerController');
    Route::resource('/shoppingwallets', 'ShoppingWalletController');
    Route::resource('/vendorwithdraws', 'VendorWithdrawController');
});

resources/views/layouts/component/Modal/ActivityCreate.blade.php
<!-- Modal -->
<div id="custom-modal" class="modal-demo col-md-4">
    <button type="button" class="close" onclick="Custombox.modal.close();">
        <span>&times;</span><span class="sr-only">Close</span>
    </button>
    <h4 class="custom-modal-title">Create New Activity</h4>
    <div class="custom-modal-text">
        <form method="POST" action="{{ route('activities.store') }}">
            @csrf
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" name="name" class="form-control" placeholder="Enter name" required>
                <small id="name" class="form-text text-muted">The name of the activity must be filled in for identification</small>
            </div>
            <div class="form-group">
                <label class="col-form-label" for="example-textarea">Description</label>
                <textarea class="form-control" name="description" rows="5" id="example-textarea"></textarea>
            </div>
            <div class="form-group">
                <label>Color</label>
                <select class="form-control" name="color" required>
                    <option value="info">Blue</option>
                    <option value="primary">Light Blue</option>
                    <option value="success">Green</option>
                    <option value="warning">Yellow</option>
                    <option value="danger">Red</option>
                    <option value="purple">Purple</option>
                    <option value="pink">Pink</option>
                    <option value="dark">Dark</option>
                </select>
            </div>
            <button type="submit" class="btn btn-primary">Create</button>
        </form>
    </div>
</div>
</div>

resources/views/layouts/component/Modal/CustomerCreate.blade.php
  <div class="modal fade" id="customerCreateModal" tabindex="-1" role="dialog" aria-labelledby="customerCreateModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
          <div class="modal-content">
              <div class="modal-header bg-secondary">
                  <h5 class="modal-title text-white" id="customerCreateLabel">Create New Customer</h5>
                  <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                  </button>
              </div>
              <form id="customerCreateForm" method="POST" action="{{ route('customers.store') }}">
                  @csrf
                  <div class="modal-body">
                      <div class="form-group">
                          <label for="task">Task</label>
                          <input type="text" name="task" class="form-control" placeholder="Enter Task" required>
                      </div>
                      <div class="form-group">
                          <label for="card_id">Assignee</label>
                          <select name="user_id[]" class="select2 select2-multiple" multiple="multiple" multiple data-placeholder="Choose ...">
                              @foreach($users as $res)
                              <option value="{{ $res->id }}">{{ $res->name }}</option>
                              @endforeach
                          </select>
                      </div>
                      <div class="form-group">
                          <div class="row">
                              <div class="col-6">
                                  <label for="mitra">Paket Mitra</label>
                                  <select name="package" id="mitra" class="form-control" required>
                                      <option value="" selected>&mdash;</option>
                                      @php
                                      $mitras = [
                                      [
                                      "name" => "Universal",
                                      "price" => "50000",
                                      ],
                                      [
                                      "name" => "Branding",
                                      "price" => "599000",
                                      ],
                                      [
                                      "name" => "Professional",
                                      "price" => "3000000",
                                      ]
                                      ];
                                      @endphp
                                      @foreach($mitras as $mitra)
                                      <option value="{{ $mitra['name'] }}" price="{{ $mitra['price'] }}">{{ $mitra['name'] }}</option>
                                      @endforeach
                                  </select>
                              </div>
                              <div class="col-6">
                                  <label for="harga">Harga</label>
                                  <input type="number" name="price" id="price" class="form-control" placeholder="Harga" required>
                              </div>
                          </div>
                      </div>
                      <div class="form-group">
                          <div class="row">
                              <div class="col-md-6">
                                  <div class="form-group">
                                      <label>Tanggal Close</label>
                                      <input id="date-close" name="date_close" type="text" class="form-control" name="date_close" required>
                                      <span class="font-13 text-muted">e.g "MM/DD/YYYY"</span>
                                  </div>
                              </div>
                              <div class="col-6">
                                  <label for="priority">Priority</label>
                                  <select name="priority" id="priority" class="form-control" required>
                                      <option value="" selected>&mdash;</option>
                                      @php
                                      $priorities = ["Urgent", "High", "Normal", "Low", "Additional"];
                                      @endphp
                                      @foreach($priorities as $res)
                                      <option value="{{ $res }}">{{ $res }}</option>
                                      @endforeach
                                  </select>
                              </div>
                          </div>
                      </div>
                      <div class="form-group">
                          <div class="form-group">
                              <label for="payment">Payment</label>
                              <select name="payment" class="form-control" placeholder="Payment" required>
                                  <optgroup label="Bank Transfer Manual"></optgroup>
                                  <option value="Bank BCA">Bank BCA</option>
                                  <option value="Bank BNI">Bank BNI</option>
                                  <option value="Bank MANDIRI">Bank MANDIRI</option>
                                  <option value="Bank BRI">Bank BRI</option>
                                  <option value="Bank BTN">Bank BTN</option>
                                  <option value="Bank BTPN">Bank BTPN</option>
                                  <option value="Bank CIMB">Bank CIMB</option>
                                  <option value="Bank BJB">Bank BJB</option>
                                  <option value="Bank DANAMON">Bank DANAMON</option>
                                  <option value="Bank DBS">Bank DBS</option>
                                  <option value="Bank Muamalat">Bank Muamalat</option>
                                  <option value="Bank Sinarmas">Bank Sinarmas</option>
                                  <option value="Bank Lainnya">Bank Lainnya</option>
                                  </optgroup>
                                  <optgroup label="Xendit"></optgroup>
                                  <option value="Xendit Alfamart">Alfamart</option>
                                  <option value="Xendit Virtual Account">Virtual Account</option>
                                  <option value="Xendit OVO">OVO</option>
                                  <optgroup label="Lainnya"></optgroup>
                                  <option value="Pulsa">Pulsa</option>
                              </select>
                          </div>
                      </div>
                      <div class="form-group">
                          <div class="form-group">
                              <label for="comment">Comment</label>
                              <textarea name="comment" id="comment" class="form-control"></textarea>
                          </div>
                      </div>
                  </div>
                  <div class="modal-footer">
                      <button type="submit" class="btn btn-primary rounded">Submit</button>
                  </div>
              </form>
          </div>
      </div>
  </div>

  <script>
      let selectMitra = document.getElementById('mitra')

      selectMitra.addEventListener('change', function() {
          let inputPrice = document.getElementById('price')
          inputPrice.value = selectMitra.options[this.selectedIndex].getAttribute('price')
      })
  </script>

resources/views/layouts/component/Modal/EditTask.blade.php
  <!-- Modal -->
  <div class="modal fade" id="editTaskModal" tabindex="-1" role="dialog" aria-labelledby="addTaskModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header bg-secondary">
          <h5 class="modal-title text-white" id="addTaskModalLabel">Task Detail</h5>
          <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form id="editTaskForm" method="POST" action="">
        @csrf
        {{ method_field('PUT') }}
        <div class="modal-body">
            <div class="form-group">
                <label for="card_id">Users Tasks</label>
                <select id="IUserTasks" name="usertasks[]" class="select2 select2-multiple" multiple="multiple" multiple data-placeholder="Choose ..."></select>  
            </div>
            <hr>
            <div class="form-group">
                <label for="card_id">Move Task To Card</label>
                <br><button id="btnMoveTaskToCard" type="button" class="btn btn-sm btn-primary">Move</button>
                <select id="selectMoveTaskToCard" name="" class="form-control">
                    @foreach($cards as $res)
                        <option value="{{ $res->id }}">{{ $res->name }}</option>
                    @endforeach
                </select>
            </div>
            <hr>
            <div class="form-group">
                <div class="row">
                    <div class="col-md-6">
                        <label for="card_id">Card Name</label>
                        <input id="IECardName" type="text" class="form-control" disabled>
                    </div>
                    <div class="col-md-6">
                        <label for="priority">Priority</label>
                        <select name="priority" id="priority" class="form-control" required>
                            <option id="IPriority" selected></option>
                            @php
                                $priorities = ["Urgent", "High", "Normal", "Low", "Additional"];
                            @endphp
                            @foreach($priorities as $res)
                            <option value="{{ $res }}">{{ $res }}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
            </div>
            <div class="form-group">  
                <label for="name">Name</label>
                <input id="IName" type="text" name="name" class="form-control" placeholder="Enter name" required>
            </div>
            <div class="form-group">
                <label class="col-form-label" for="example-textarea">Description</label>
                <textarea id="IDescription" class="form-control" name="description" rows="5" id="example-textarea"></textarea>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Started At</label>
                            <input id="IStartedAt" type="text" class="form-control" name="started_at" required>
                            <span class="font-13 text-muted">e.g "MM/DD/YYYY"</span>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Ended At</label>
                            <input id="IEndedAt" type="text" class="form-control" name="ended_at" required>
                            <span class="font-13 text-muted">e.g "MM/DD/YYYY"</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <a href="#" class="btn btn-danger" onclick="document.getElementById('IFormRemoveTask').submit()">Remove Task</a>
            <button type="submit" class="btn btn-primary rounded">Submit</button>
        </div>
        </form>

        <form id="IFormRemoveTask" method="POST" action="" style="display:none;">
            @csrf
            {{ method_field('DELETE') }}
        </form>
      </div>
    </div>
  </div>

resources/views/layouts/component/Modal/ModalComment.blade.php
<div class="modal fade" id="modalComment" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog confirm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">View Comment</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div id="showComment" class="modal-body">

            </div>
        </div>
    </div>
</div>

resources/views/layouts/component/Modal/ModalDestroy.blade.php
<div class="modal fade" id="modalDestroy" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog confirm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Delete Confirmation</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Are you sure you want to remove?
                <br><br>
                <div class="row">
                    <div class="col-12 text-right">
                        <form id="deleteConf" method="POST" action="">
                            @csrf
                            {{ method_field('DELETE') }}
                            <button type="submit" class="btn btn-danger">Yes, delete it</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/layouts/component/Modal/NewCard.blade.php
<!-- Modal -->
<div id="new_card" class="modal-demo col-md-4">
    <button type="button" class="close" onclick="Custombox.modal.close();">
        <span>&times;</span><span class="sr-only">Close</span>
    </button>
    <h4 class="custom-modal-title">Add New Card</h4>
    <div class="custom-modal-text">
        <form method="POST" action="{{ route('cards.store') }}">
            @csrf
            <input type="hidden" name="activity_id" value="{{ $activity->id }}">
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" name="name" class="form-control" placeholder="Enter name" required>
            </div>
            <button type="submit" class="btn btn-primary rounded">Submit</button>
        </form>
    </div>
</div>
</div>

resources/views/layouts/component/Modal/NewTask.blade.php
  <!-- Modal -->
  <div class="modal fade" id="addTaskModal" tabindex="-1" role="dialog" aria-labelledby="addTaskModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header bg-secondary">
          <h5 class="modal-title text-white" id="addTaskModalLabel">Add New Task</h5>
          <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form method="POST" action="{{ route('tasks.store') }}">
        @csrf
        <input id="ICardId" type="hidden" name="card_id">
        <div class="modal-body">
            <div class="form-group">
                <div class="row">
                    <div class="col-md-6">
                        <label for="card_id">Card Name</label>
                        <input id="ICardName" type="text" class="form-control" disabled>
                    </div>
                    <div class="col-md-6">
                        <label for="priority">Priority</label>
                        <select name="priority" id="priority" class="form-control" required>
                            <option value="" selected>&mdash;</option>
                            @php
                                $priorities = ["Urgent", "High", "Normal", "Low", "Additional"];
                            @endphp
                            @foreach($priorities as $res)
                            <option value="{{ $res }}">{{ $res }}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
            </div>
            <div class="form-group">  
                <label for="name">Name</label>
                <input type="text" name="name" class="form-control" placeholder="Enter name" required>
            </div>
            <div class="form-group">
                <label class="col-form-label" for="example-textarea">Description</label>
                <textarea class="form-control" name="description" rows="5" id="example-textarea"></textarea>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Started At</label>
                            <input type="text" class="form-control" id="datepicker-startedat" name="started_at" required>
                            <span class="font-13 text-muted">e.g "MM/DD/YYYY"</span>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Ended At</label>
                            <input type="text" class="form-control" id="datepicker-endedat" name="ended_at" required>
                            <span class="font-13 text-muted">e.g "MM/DD/YYYY"</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
        </form>
      </div>
    </div>
  </div>

resources/views/layouts/component/Modal/ShoppingWalletCreate.blade.php
<div class="modal fade" id="shoppingWalletCreateModal" tabindex="-1" role="dialog" aria-labelledby="shoppingWalletCreateModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header bg-secondary">
                <h5 class="modal-title text-white" id="shoppingWalletCreateLabel">Create New Shopping Wallet Report</h5>
                <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="shoppingWalletCreateForm" method="POST" action="{{ route('shoppingwallets.store') }}">
                @csrf
                <div class="modal-body">
                    <div class="form-group">
                        <label for="task">Task</label>
                        <input type="text" name="task" class="form-control" placeholder="Enter Task" required>
                    </div>
                    <div class="form-group">
                        <label for="card_id">Assignee</label>
                        <select name="user_id[]" class="select2 select2-multiple" multiple="multiple" multiple data-placeholder="Choose ...">
                            @foreach($users as $res)
                            <option value="{{ $res->id }}">{{ $res->name }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="nominal">Nominal</label>
                        <input type="number" name="nominal" id="nominal" class="form-control" placeholder="Nominal" required>
                    </div>
                    <div class="form-group">
                        <label>Date</label>
                        <input id="date-close" name="date" type="text" class="form-control" required>
                        <span class="font-13 text-muted">e.g "MM/DD/YYYY"</span>
                    </div>
                    <div class="form-group">
                        <div class="form-group">
                            <label for="payment">Payment</label>
                            <select name="payment" class="form-control" placeholder="Payment" required>
                                <optgroup label="Bank Transfer Manual"></optgroup>
                                <option value="Bank BCA">Bank BCA</option>
                                <option value="Bank BNI">Bank BNI</option>
                                <option value="Bank MANDIRI">Bank MANDIRI</option>
                                <option value="Bank BRI">Bank BRI</option>
                                <option value="Bank BTN">Bank BTN</option>
                                <option value="Bank BTPN">Bank BTPN</option>
                                <option value="Bank CIMB">Bank CIMB</option>
                                <option value="Bank BJB">Bank BJB</option>
                                <option value="Bank DANAMON">Bank DANAMON</option>
                                <option value="Bank DBS">Bank DBS</option>
                                <option value="Bank Muamalat">Bank Muamalat</option>
                                <option value="Bank Sinarmas">Bank Sinarmas</option>
                                <option value="Bank Lainnya">Bank Lainnya</option>
                                </optgroup>
                                <optgroup label="Xendit"></optgroup>
                                <option value="Xendit Alfamart">Alfamart</option>
                                <option value="Xendit Virtual Account">Virtual Account</option>
                                <option value="Xendit OVO">OVO</option>
                                <optgroup label="Lainnya"></optgroup>
                                <option value="Pulsa">Pulsa</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary rounded">Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    let selectMitra = document.getElementById('mitra')

    selectMitra.addEventListener('change', function() {
        let inputPrice = document.getElementById('price')
        inputPrice.value = selectMitra.options[this.selectedIndex].getAttribute('price')
    })
</script>

resources/views/layouts/component/Modal/VendorWithdrawCreate.blade.php
<div class="modal fade" id="vendorWithdrawCreateModal" tabindex="-1" role="dialog" aria-labelledby="vendorWithdrawCreateModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header bg-secondary">
                <h5 class="modal-title text-white" id="vendorWithdrawCreateLabel">Create New Vendor Withdraw</h5>
                <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="vendorWithdrawCreateForm" method="POST" action="{{ route('vendorwithdraws.store') }}">
                @csrf
                <div class="modal-body">
                    <div class="form-group">
                        <label for="task">Task</label>
                        <input type="text" name="task" class="form-control" placeholder="Enter Task" required>
                    </div>
                    <div class="form-group">
                        <label for="card_id">Assignee</label>
                        <select name="user_id[]" class="select2 select2-multiple" multiple="multiple" multiple data-placeholder="Choose ...">
                            @foreach($users as $res)
                            <option value="{{ $res->id }}">{{ $res->name }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="nominal">Jumlah</label>
                        <input type="number" name="nominal" id="nominal" class="form-control" placeholder="Jumlah" required>
                    </div>
                    <div class="form-group">
                        <label for="payment">Bank</label>
                        <select name="payment" class="form-control" placeholder="Payment" required>
                            <optgroup label="Bank Transfer Manual"></optgroup>
                            <option value="Bank BCA">Bank BCA</option>
                            <option value="Bank BNI">Bank BNI</option>
                            <option value="Bank MANDIRI">Bank MANDIRI</option>
                            <option value="Bank BRI">Bank BRI</option>
                            <option value="Bank BTN">Bank BTN</option>
                            <option value="Bank BTPN">Bank BTPN</option>
                            <option value="Bank CIMB">Bank CIMB</option>
                            <option value="Bank BJB">Bank BJB</option>
                            <option value="Bank DANAMON">Bank DANAMON</option>
                            <option value="Bank DBS">Bank DBS</option>
                            <option value="Bank Muamalat">Bank Muamalat</option>
                            <option value="Bank Sinarmas">Bank Sinarmas</option>
                            <option value="Bank Lainnya">Bank Lainnya</option>
                            </optgroup>
                            <optgroup label="Xendit"></optgroup>
                            <option value="Xendit Alfamart">Alfamart</option>
                            <option value="Xendit Virtual Account">Virtual Account</option>
                            <option value="Xendit OVO">OVO</option>
                            <optgroup label="Lainnya"></optgroup>
                            <option value="Pulsa">Pulsa</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <div class="form-group">
                            <label>Tanggal</label>
                            <input id="date-close" name="date" type="text" class="form-control" name="date_close" required>
                            <span class="font-13 text-muted">e.g "MM/DD/YYYY"</span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="form-group">
                            <label for="comment">Comment</label>
                            <textarea name="comment" id="comment" class="form-control"></textarea>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary rounded">Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>