routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route("home");
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/test-statistic', 'HomeController@test_statistic')->name('test-statistic');

Route::group(["prefix" => "app", "middleware" => "auth"], function () {
    Route::resource('/profile', 'ProfileController');
    Route::resource('/useractivities', 'UserActivityController');
    Route::resource('/activities', 'ActivityController');
    Route::resource('/cards', 'CardController');
    Route::resource('/tasks', 'TaskController');
    Route::resource('/customers', 'CustomerController');
    Route::resource('/shoppingwallets', 'ShoppingWalletController');
    Route::resource('/vendorwithdraws', 'VendorWithdrawController');
});

resources/views/layouts/component/alert.blade.php
@if(session("alertStore"))
<script>
    Swal.fire({
        title:"Data has been added!",
        text:"{{ session('alertStore') }}",
        type:"success",
        confirmButtonClass:"btn btn-confirm mt-2"
    })
</script>
@elseif(session("alertUpdate"))
<script>
    Swal.fire({
        title:"Data has been updated!",
        text:"{{ session('alertUpdate') }}",
        type:"success",
        confirmButtonClass:"btn btn-confirm mt-2"
    })
</script>
@elseif(session("alertDestroy"))
<script>
    Swal.fire({
        title:"Data has been deleted!",
        text:"{{ session('alertDestroy') }}",
        type:"success",
        confirmButtonClass:"btn btn-confirm mt-2"
    })
</script>
@endif

resources/views/layouts/component/footer.blade.php
<footer class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6">
                @php date('Y'); @endphp &copy; INDOHP Task Report</a>
            </div>
        </div>
    </div>
</footer>

resources/views/layouts/component/head.blade.php
<meta charset="utf-8" />
<title>INDOHP Task Report</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta content="PT Indonesia Hakiki Pertama -- Task Report" name="description" />
<meta content="Coderthemes" name="author" />
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<!-- App favicon -->
<link rel="shortcut icon" href="{{asset('assets/images/favicon.ico')}}">

@yield('customCSS')

<!-- Sweet Alert-->
<link href="{{asset('assets/libs/sweetalert2/sweetalert2.min.css')}}" rel="stylesheet"/>

<!-- App css -->
<link href="{{asset('/assets/css/bootstrap.min.css')}}" rel="stylesheet" />
<link href="{{asset('/assets/css/icons.min.css')}}" rel="stylesheet" />
<link href="{{asset('/assets/css/app.min.css')}}" rel="stylesheet" />

resources/views/layouts/component/script.blade.php
<!-- Vendor js -->
<script src="{{asset('assets/js/vendor.min.js')}}"></script>

@yield('customJS')

<!-- App js -->
<script src="{{ asset('js/modal-destroy.js') }}"></script>
<script src="{{asset('assets/js/app.min.js')}}"></script>

resources/views/layouts/component/sidebar.blade.php
<div class="left-side-menu">

    <div class="slimscroll-menu">

        <!-- User box -->
        <div class="user-box text-center">
            @if(!empty(Auth::user()->avatar))
            <img src="{{ asset('img/avatar/' . Auth::user()->avatar) }}" alt="user-img" title="{{ Auth::user()->name }}" class="rounded-circle img-thumbnail avatar-lg">
            @else
            <img src="{{asset('img/user-default.jpg')}}" alt="user-img" title="{{ Auth::user()->name }}" class="rounded-circle img-thumbnail avatar-lg">
            @endif
            <div class="dropdown">
                <a href="#" class="text-dark dropdown-toggle h5 mt-2 mb-1 d-block" data-toggle="dropdown">{{ Auth::user()->name }}</a>
            </div>
            <p class=" text-muted">INDOHP Task Report</p>
            <ul class="list-inline">
                <li class="list-inline-item"></li>
            </ul>
        </div>

        <!--- Sidemenu -->
        <div id="sidebar-menu">

            <ul class="metismenu" id="side-menu">

                <li class="menu-title">Menu App</li>

                <li id="dashboards">
                    <a href="{{route('home')}}">
                        <i class="mdi mdi-view-dashboard"></i>
                        <span> Dashboard </span>
                    </a>
                </li>

                <li>
                    <a href="javascript: void(0);">
                        <i class="mdi mdi-calendar"></i>
                        <span> Activities </span>
                        <span class="menu-arrow"></span>
                    </a>
                    <ul class="nav-second-level" aria-expanded="false">
                        @php
                        $activities = \App\Model\Activity::orderBy("id", "DESC")->get();
                        @endphp
                        <li><a href="{{ route('activities.index') }}">All Activities</a></li>
                        @foreach($activities as $res)
                        <li><a href="{{ route('cards.index') }}?activity_id={{ $res->id }}">{{ $res->name }}</a></li>
                        @endforeach
                    </ul>
                </li>

                <li id="customers">
                    <a href="{{route('customers.index')}}">
                        <i class="mdi mdi-account-box-multiple"></i>
                        <span> Mitra Bayar</span>
                    </a>
                </li>

                <li id="shoppingwallets">
                    <a href="{{route('shoppingwallets.index')}}">
                        <i class="mdi mdi-wallet-outline"></i>
                        <span> Topup Dompet Belanja</span>
                    </a>
                </li>

                <li id="vendorWithdraws">
                    <a href="{{route('vendorwithdraws.index')}}">
                        <i class="mdi mdi-wallet-outline"></i>
                        <span> Vendor Withdraw</span>
                    </a>
                </li>


                <li class="menu-title">Account</li>

                <li id="dashboards">
                    <a href="#" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                        <i class="mdi mdi-logout-variant"></i>
                        <span> Logout </span>
                    </a>

                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        @csrf
                    </form>
                </li>
            </ul>

        </div>
        <!-- End Sidebar -->

        <div class="clearfix"></div>

    </div>
    <!-- Sidebar -left -->

</div>

resources/views/layouts/component/topbar.blade.php
<div class="navbar-custom">
    <ul class="list-unstyled topnav-menu float-right mb-0">

        <li class="d-none d-sm-block">
            <form class="app-search">
                <div class="app-search-box">
                    <div class="input-group">
                        <input type="text" class="form-control" name="q" placeholder="Search...">
                        <div class="input-group-append">
                            <button class="btn" type="submit">
                                <i class="fe-search"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </form>
        </li>

        <li class="dropdown notification-list">
            <a class="nav-link dropdown-toggle nav-user mr-0 waves-effect" data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
                @if(!empty(Auth::user()->avatar))
                <img src="{{ asset('img/avatar/'.Auth::user()->avatar) }}" alt="user-image" class="rounded-circle">
                @else
                <img src="{{ asset('img/user-default.jpg') }}" alt="user-image" class="rounded-circle">
                @endif
                <span class="pro-user-name ml-1">
                    {{ Auth::user()->name }} <i class="mdi mdi-chevron-down"></i>
                </span>
            </a>
            <div class="dropdown-menu dropdown-menu-right profile-dropdown" style="">
                <!-- item-->
                <div class="dropdown-header noti-title">
                    <h6 class="text-overflow m-0">My Account</h6>
                </div>

                <!-- item-->
                <a href="{{ route('profile.index') }}" class="dropdown-item notify-item">
                    <i class="fe-user"></i>
                    <span>My Account</span>
                </a>

                <div class="dropdown-divider"></div>

                <!-- item-->
                <a href="#" onclick="event.preventDefault(); document.getElementById('logout-form').submit();" class="dropdown-item notify-item">
                    <i class="fe-log-out"></i>
                    <span>Logout</span>
                </a>
                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>

            </div>
        </li>


    </ul>

    <!-- LOGO -->
    <div class="logo-box">
        <a href="index-2.html" class="logo text-center">
            <span class="logo-lg">
                <img src="{{asset('assets/images/logo-dark.png')}}" alt="" height="26">
                <!-- <span class="logo-lg-text-light">Xeria</span> -->
            </span>
            <span class="logo-sm">
                <!-- <span class="logo-sm-text-dark">X</span> -->
                <img src="{{asset('assets/images/logo-sm.png')}}" alt="" height="24">
            </span>
        </a>
    </div>

    <ul class="list-unstyled topnav-menu topnav-menu-left m-0">
        <li>
            <button class="button-menu-mobile disable-btn waves-effect">
                <i class="fe-menu"></i>
            </button>
        </li>

        <li>
            <h4 class="page-title-main">INDOHP Task Report</h4>
        </li>

    </ul>
</div>